version: 1.0.{build}
image:
  - Ubuntu
  - Visual Studio 2019
skip_tags: true
configuration: Release
before_build:
  - ps: dotnet restore
build:
  project: PuppeteerSharp.Renderer.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: minimal
after_build:
  - ps: dotnet publish .\PuppeteerSharp.RendererCli -p:PublishProfile=PuppeteerSharp.RendererCliWindows

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}-prerelease"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

artifacts:
  - path: '**\PuppeteerSharp.Renderer.*.*nupkg'
    name: PuppeteerSharp.RendererNuget

  - path: '**\PuppeteerSharp.RendererCli.exe'
    name: PuppeteerSharp.RendererCli

deploy:
  - provider: NuGet
    api_key:
      secure: /G1AWAN6rAx8wnb36AM3XpYDyK9cVtfa3RdOsDYSw+Pxmy8AjztIGL7Zoo8nIikw
    skip_symbols: false
    on:
      branch: main
    artifact: /.*(\.|\.s)nupkg/
  - provider: GitHub
    auth_token:
      secure: tio44a4PvWOdIHek43DoVSy8qygQwPpINw+foze+eGE8hysjNI0VVKxKkmj4GLQc
    artifact: PuppeteerSharp.RendererNuget,PuppeteerSharp.RendererCli
    on:
      branch: main
