version: 1.1.{build}
environment:
  # Windows specific setting
  nodejs_version: "12"
image:
  - Ubuntu
  - Visual Studio 2019
skip_tags: true
configuration: Release
before_build:
  - ps: dotnet restore
install:
  # Windows specific setting
  - ps: if ($IsWindows -or $ENV:OS) { Install-Product node '12' x64 } 
  - ps: node --version
  - ps: node -p "process.arch"
  - ps: npm --version
after_build:
  - ps: dotnet publish .\PuppeteerSharp.RendererCli -p:PublishProfile=PuppeteerSharp.RendererCliWindows

build:
  project: PuppeteerSharp.Renderer.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: minimal

# Linux specific setting
stack: node 10

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

artifacts:
  - path: '**\PuppeteerSharp.Renderer.*.*nupkg'
    name: PuppeteerSharp.RendererNuget

  - path: PuppeteerSharp.RendererCli\bin\Release\net5.0\publish\PuppeteerSharp.RendererCli.exe
    name: PuppeteerSharp.RendererCli

deploy:
  - provider: NuGet
    api_key:
      secure: CTISdGCfnpyC7Rh5vs1pgbuISrkWF34sot0SyVgvu0HQxhNNd+V0Gc4MS+rtJttB
    skip_symbols: false
    on:
      branch: main
    artifact: /.*(\.|\.s)nupkg/
  - provider: GitHub
    auth_token:
      secure: tio44a4PvWOdIHek43DoVSy8qygQwPpINw+foze+eGE8hysjNI0VVKxKkmj4GLQc
    artifact: PuppeteerSharp.RendererNuget,PuppeteerSharp.RendererCli
    on:
      branch: main
