version: 1.0.{build}
environment:
  # Windows specific setting
  nodejs_version: "12"
image:
  - Ubuntu
  - Visual Studio 2019
skip_tags: true
configuration: Release
install:
  # Windows specific setting
  - ps: if ($IsWindows -or $ENV:OS) { Install-Product node '12' x64 } 
  - ps: node --version
  - ps: node -p "process.arch"
  - ps: npm --version
after_build:
  - ps: dotnet publish .\PuppeteerSharp.RendererCli -p:PublishProfile=PuppeteerSharp.RendererCliWindows

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}-prerelease"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

artifacts:
  - path: '**\PuppeteerSharp.Renderer.*.*nupkg'
    name: PuppeteerSharp.RendererNuget

  - path: '**\PuppeteerSharp.RendererCli.exe'
    name: PuppeteerSharp.RendererCli

deploy:
  - provider: NuGet
    api_key:
      secure: /G1AWAN6rAx8wnb36AM3XpYDyK9cVtfa3RdOsDYSw+Pxmy8AjztIGL7Zoo8nIikw
    skip_symbols: false
    on:
      branch: main
    artifact: /.*(\.|\.s)nupkg/
  - provider: GitHub
    auth_token:
      secure: tio44a4PvWOdIHek43DoVSy8qygQwPpINw+foze+eGE8hysjNI0VVKxKkmj4GLQc
    artifact: PuppeteerSharp.RendererNuget,PuppeteerSharp.RendererCli
    on:
      branch: main
