name: .NET build and test
env:
  CURRENT_VERSION: 4.0.${{ github.run_number }}
  LAST_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            10.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish FolderProfilePortable
        run: dotnet publish ./Codeuctivity.HtmlRendererCli --configuration Release -f net10.0 -p:PublishProfile=FolderProfilePortable
      - name: Publish FolderProfileWindows
        run: dotnet publish ./Codeuctivity.HtmlRendererCli --configuration Release -f net10.0 -p:PublishProfile=FolderProfileWindows
      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release
      - name: Publish Unit Test Results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: TestResult
          path: "TestResult/**/*"

  deployRelease:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            10.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish FolderProfilePortable
        run: dotnet publish ./Codeuctivity.HtmlRendererCli --configuration Release -f net10.0 -p:PublishProfile=FolderProfilePortable
      - name: Publish FolderProfileWindows
        run: dotnet publish ./Codeuctivity.HtmlRendererCli --configuration Release -f net10.0 -p:PublishProfile=FolderProfileWindows
      - name: Zip FolderProfilePortable
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          directory: ./Codeuctivity.HtmlRendererCli/bin/Release/net10.0/publish/FolderProfilePortable
          filename: 'Codeuctivity.HtmlRendererCli.Portable.zip'
      - name: NugetPush
        env:
          NUGET_TOKEN_EXISTS: ${{ secrets.NUGET_TOKEN }}
        if: env.NUGET_TOKEN_EXISTS != ''
        run: |
          dotnet nuget push ./Codeuctivity.HtmlRenderer/bin/Release/*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
      - name: Github Release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        if:  env.GITHUB_TOKEN != ''
        run: |
            gh release create ${{env.CURRENT_VERSION}} ./Codeuctivity.HtmlRenderer/bin/Release/*.*nupkg ./Codeuctivity.HtmlRendererCli/bin/Release/net10.0/publish/FolderProfilePortable/Codeuctivity.HtmlRendererCli.Portable.zip ./Codeuctivity.HtmlRendererCli/bin/Release/net10.0/publish/FolderProfileWindows/Codeuctivity.HtmlRendererCli.exe --generate-notes
  
  deployTest:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            10.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish FolderProfilePortable
        run: dotnet publish ./Codeuctivity.HtmlRendererCli --configuration Release -f net10.0 -p:PublishProfile=FolderProfilePortable
      - name: Publish FolderProfileWindows
        run: dotnet publish ./Codeuctivity.HtmlRendererCli --configuration Release -f net10.0 -p:PublishProfile=FolderProfileWindows
      - name: Zip FolderProfilePortable
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          directory: ./Codeuctivity.HtmlRendererCli/bin/Release/net10.0/publish/FolderProfilePortable
          filename: 'Codeuctivity.HtmlRendererCli.Portable.zip'
      - name: NugetPush
        env:
          NUGET_TOKEN_EXISTS: ${{ secrets.NUGET_TEST_TOKEN }}
        if: env.NUGET_TOKEN_EXISTS != ''
        run: |
          ls ./Codeuctivity.HtmlRenderer/bin/Release
          dotnet nuget push ./Codeuctivity.HtmlRenderer/bin/Release/*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_TEST_TOKEN}} --source https://apiint.nugettest.org/v3/index.json

      - name: Github Prerelease
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        if:  env.GITHUB_TOKEN != ''
        run: |
            gh release create ${{env.CURRENT_VERSION}} ./Codeuctivity.HtmlRenderer/bin/Release/*.*nupkg ./Codeuctivity.HtmlRendererCli/bin/Release/net10.0/publish/FolderProfilePortable/Codeuctivity.HtmlRendererCli.Portable.zip ./Codeuctivity.HtmlRendererCli/bin/Release/net10.0/publish/FolderProfileWindows/Codeuctivity.HtmlRendererCli.exe --prerelease --generate-notes
